### ISSUE TITLE
get_formkey fails

### ISSUE THREAD

**Issue by johnd0e** [x404xx/POE-Api#2]
Solution: pass headers here:
https://github.com/x404xx/POE-Api/blob/076559f4d923aad9a86b62c44eb82afd4a8a6679/api.py#L59

Ref: https://github.com/snowby666/poe-api-wrapper/blob/2c49bdf7287e95257d17f68a581275b1f74b476c/api.py#L62

**Comment by x404xx** [comment]
> Solution: pass headers here:
> 
> https://github.com/x404xx/POE-Api/blob/076559f4d923aad9a86b62c44eb82afd4a8a6679/api.py#L59
> 
> Ref: https://github.com/snowby666/poe-api-wrapper/blob/2c49bdf7287e95257d17f68a581275b1f74b476c/api.py#L62

Thanks for pointing that out. Now, the 'get_formkey' method should work. As for the chatbot, I'm not sure if it's still working because I'm not maintaining it anymore.

**Comment by johnd0e** [comment]
> As for the chatbot, I'm not sure if it's still working 

Unfortunately it doesn't..

> because I'm not maintaining it anymore.

Too bad..
Fortunately, there is working alternative repo https://github.com/snowby666/poe-api-wrapper
